/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_friendlyarm_FriendlyThings_HardwareController */

#ifndef _Included_com_friendlyarm_FriendlyThings_HardwareController
#define _Included_com_friendlyarm_FriendlyThings_HardwareController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    setGPIOValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_setGPIOValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    getGPIOValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_getGPIOValue
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    open
 * Signature: (III)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_open
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_close
  (JNIEnv *, jclass);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    setTxMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_setTxMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    setRxMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_setRxMode
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
