/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_friendlyarm_FriendlyThings_HardwareController */

#ifndef _Included_com_friendlyarm_FriendlyThings_HardwareController
#define _Included_com_friendlyarm_FriendlyThings_HardwareController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    setGPIOValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_setGPIOValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    getGPIOValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_getGPIOValue
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_open
  (JNIEnv *, jclass);

/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_close
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_friendlyarm_FriendlyThings_HardwareController
 * Method:    SPItransferBytes
 * Signature: (I[B[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_friendlyarm_FriendlyThings_HardwareController_SPItransferBytes
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
