/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_friendlyarm_FriendlyThings_Serial */

#ifndef _Included_com_friendlyarm_FriendlyThings_Serial
#define _Included_com_friendlyarm_FriendlyThings_Serial
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
